### PR TITLE
fix(home page): fix learn more button linking issue

### LINKED ISSUE #65: [Home Page:Re]
**Task title**
The task title

**Task description**
Home page revision & enhancement

**Subtasks**

- [ ] change link path ("learn more" button should take to requirements => therapist account)
- [x] fix some links require two clicks to show

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here

### PR DESCRIPTION
**Pull request by Zohir-kk**
fix #65
fix learn more button linking issue where it takes to therapist create instead of requirement page

#Tasks
- [x]  change link path ("learn more" button should take to requirements => therapist account)

# Description
Please include a summary of the changes you made, files created, is it page or component, is it project set up

## Type of change
Please delete options that are not relevant.
-   [x] Style
 
# Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have added tests that prove my fix is effective or that my feature works

**Files changed**:
list all file names that were created or modified (components, configs, style)

-   Home page

### CODE REVIEW

**Comment by GhaniBahri** [comment]
good job @Zohir-kk , but as mentioned in the issue subtask, the learn more takes to requirements, and the requirement should **redirect to create therapist account**

**Review by GhaniBahri — CHANGES_REQUESTED** [review]
good job @Zohir-kk , but as mentioned in the issue subtask, the learn more takes to requirements, and the requirement should redirect to create therapist account

**Review by Amel7400 — APPROVED** [review]
Good job Zohir !

**Review by GhaniBahri — APPROVED** [review]
well done! just update branch as githun required and merge it

**Pull request merged**
