### PR TITLE
Fixes/blogs

### PR DESCRIPTION
**Pull request by fketta**
**### Blogs & Admin fixes:**

**Added functionality to the admin page:**
- Delete user
- Delete blog
- Edit blog
- Reset inputs fields
- Unability to send unless all fields are filled
- Set charachter limits for title, author, and subtitle

**Fixed Blogspage errors:**
- Fixed blogs database
- Added share to social media buttons
- Fixed BlogsCarousel styling

**Other:**
- Save userdata and fetch it server side
- Turned the newsletter input field into its own component

## Type of change

Please delete options that are not relevant.

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)

# Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have added tests that prove my fix is effective or that my feature works

**Files changed**:
-/*

**Screenshots**:
image
image

### CODE REVIEW

**Review by Zohir-kk — APPROVED** [review]
Brilliant work fella your efforts are so appreciated 👏 , you just need to fix the conflicts and everything would be good to go

**Comment by fketta** [comment]
Don't merge yet please, still fixing an issue.

**Comment by fketta** [comment]
Issue fixed, review and merge when you get the chance!

**Review by Zohir-kk — APPROVED** [review]

**Review by GhaniBahri — APPROVED** [review]
thank you for the late nights hard work

**Pull request merged**
